apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::056003362194:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NP2X4MF03LAY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::056003362194:role/UdacityFlaskDeployCBKubectlRole
      username: admin
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-14T15:04:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1275"
  uid: 1efe1248-9ef1-49d5-ad1e-caf107708467
